### ISSUE TITLE
Line level editing

### ISSUE THREAD

**Issue by wlla** [NYPL/transcript-editor#18]
A user can edit a particular segment of a transcript, which will be saved to a database
* How will race conditions be handled when multiple people might edit the same segment of a transcript before one version is saved? what gets saved? what does a transcriber see during transcription? what does a transcriber see after?

**Comment by beefoo** [comment]
Implemented:

- concurrent edits to a line are okay; there is no concept of "versioning", just an algorithm that determines the line's status (e.g. "editing", "reviewing", "completed") and what is the "best" edit at any given time
- all edits gets saved
- each user gets one edit per line of a transcript; they can always "edit" that edit
- user always sees their edits (unless a line has reached consensus, then show the final text)
- line statuses are communicated via color and icons: "initialized", "editing", "reviewing", "completed"
