### ISSUE TITLE
Admin Config: What makes transcript/segment complete

### ISSUE THREAD

**Issue by wlla** [NYPL/transcript-editor#31]
An admin can configure what makes a transcript or transcript segment “complete”
Option: Define a threshold for % consensus from multiple corrections from different users
Option: An admin can manually verify/correct a transcript segment or an entire transcript

**Comment by beefoo** [comment]
Configurable in project.json:
https://github.com/NYPL/transcript-editor/blob/master/project/oral-history/project.json

(see "consensus")
