### ISSUE TITLE
Address implicit confirmation

### ISSUE THREAD

**Issue by wlla** [NYPL/transcript-editor#45]
Figure out how to handle lines that were correctly auto transcribed and never get edited
if we have an approval mode - line will turn green as you listen to the audio and assume implicit confirmation

**Comment by beefoo** [comment]
Current logic is as follows:

- implicit confirmation is always in effect; if a user looks at a line without editing, it counts as a confirmation of the existing text in that line (equivalent to typing in the text of that line)
- however, given a set of edits to a line, if there are a mix of original text (computer-generated/un-edited) and changed text, the changed text is always preferred when handling consensus
- (to be implemented) if enough people agree that the original text is the correct text, use that original text as the final text
