### ISSUE TITLE
Define concensus

### ISSUE THREAD

**Issue by wlla** [NYPL/transcript-editor#48]
On the line, chunk, and transcript level.

**Comment by beefoo** [comment]
Line-level consensus is currently defined as follows for NYPL (all numbers are configurable):

- if 3 or more unique people submit an edit to a line, that line is a candidate for consensus
- if more than 33% of people agree, that line has met consensus and is no longer editable
- if 5 or more people submitted an edit to a line, and consensus has not been reached, it will be locked for review
- (to be implemented) in the review phase, if more than 33% of people agree, that line has met consensus and is no longer editable
- (to be implemented) in review phase, if 10 or more people reviewed a line and consensus has not been reached, it will be flagged as problematic and an admin/moderator will view
- moderators and admins overrides all consensus logic: what they say goes. they can always edit a line

Transcript-level consensus logic is still pending discussion
