### ISSUE TITLE
Importing other transcript formats? (particularly WebVTT)

### ISSUE THREAD

**Issue by rtrvrtg** [NYPL/transcript-editor#70]
Hi,
I'm working for another library that is looking at evaluating your transcript tool for some of our projects. So far it looks pretty promising, but our transcripts are currently in WebVTT, and there doesn't seem to be a direct import path for that format right now.

Are there any plans on the cards to support other formats? I've had a little look through the codebase and the Pop Up Archive import process seems pretty straightforward, so if you like I might be able to have a go at writing a WebVTT importer for you. Either way, please let me know.

**Comment by beefoo** [comment]
Yes, the plan was to add support for other formats based on demand.  I think WebVTT is an obvious format that we'd like to support.  I could put together the bones for a WebVTT importer today, and you can take a stab at it if you'd like.  Otherwise, I'd probably have time in the next week or so.  As you noted, I believe it would be pretty straightforward, mirroring the Pop Up Archive import process.

**Comment by rtrvrtg** [comment]
I've been looking at the webvtt-ruby gem to do a simple conversion of our VTTs to your line-by-line format. If you've got something in mind for the workflow that could just have the guts filled in, as it were, I wouldn't mind giving it a go. There are a few things I'm not sure about - such as what to do about VTT Style markers, or how to handle speaker IDs - but that shouldn't get in the way of me getting something basic going.

**Comment by beefoo** [comment]
Great- let me look into that gem.  I generally try not to add more dependencies, but if it works out of the box, it may be worth it.  Good point on the speakers-- the app does support speaker identification, but it's currently not part of the import process.  It wouldn't be too difficult to implement.  I'll keep you posted once I make the scaffolding.

**Comment by beefoo** [comment]
Also, we're interested to hear about how other libraries and organizations might use this tool.  Feel free to drop me an email (brianfoo@nypl.org) to chat more about your potential use case.

**Comment by beefoo** [comment]
WebVTT support has been added: https://github.com/NYPL/transcript-editor#importing-existing-transcripts
