### ISSUE TITLE
ActiveRecord::PendingMigrationError issue installation

### ISSUE THREAD

**Issue by johnfelipe** [NYPL/transcript-editor#84]
This is my installation steps

https://docs.google.com/document/d/1ycdxetRFYWWnJJ0hY1NxspqnlsdeiQ2eNVizwVdOSTU/edit?usp=sharing

and show me this:

![installationissue](https://cloud.githubusercontent.com/assets/428820/16974705/e19d8c82-4e04-11e6-8fbb-dc6b336fd223.png)

How can i solved?

**Comment by beefoo** [comment]
It looks like your database migration didn't run properly.  What is the output when you run `rake db:migrate`?

**Comment by johnfelipe** [comment]
this is log

https://gist.github.com/johnfelipe/bd05c591dcdbfb3ffd8eb17f3093bfa6

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~/transcript-editor$ rails s -b 0.0.0.0 -p 3016
	=> Booting WEBrick
	=> Rails 4.2.5 application starting in development on http://0.0.0.0:3016
	=> Run `rails server -h` for more startup options
	=> Ctrl-C to shutdown server
	[2016-07-15 07:16:29] INFO  WEBrick 1.3.1
	[2016-07-15 07:16:29] INFO  ruby 2.1.2 (2014-05-08) [i686-linux]
	[2016-07-15 07:16:29] INFO  WEBrick::HTTPServer#start: pid=14377 port=3016




	Started GET "/" for 181.136.243.82 at 2016-07-15 07:16:34 -0500
	Started GET "/" for 181.136.243.82 at 2016-07-15 07:16:34 -0500

	ActiveRecord::PendingMigrationError (

	Migrations are pending. To resolve this issue, run:

			bin/rake db:migrate RAILS_ENV=development

	):
	  activerecord (4.2.5) lib/active_record/migration.rb:392:in `check_pending!'
	  activerecord (4.2.5) lib/active_record/migration.rb:373:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
	  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
	  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
	  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
	  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
	  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
	  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
	  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
	  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  rack (1.6.4) lib/rack/lock.rb:17:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  railties (4.2.5) lib/rails/engine.rb:518:in `call'
	  railties (4.2.5) lib/rails/application.rb:165:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  rack (1.6.4) lib/rack/lock.rb:17:in `call'
	  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
	  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
	  /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	  /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	  /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'



	ActiveRecord::PendingMigrationError (

	Migrations are pending. To resolve this issue, run:

			bin/rake db:migrate RAILS_ENV=development

	):
	  activerecord (4.2.5) lib/active_record/migration.rb:392:in `check_pending!'
	  activerecord (4.2.5) lib/active_record/migration.rb:373:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
	  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
	  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
	  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
	  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
	  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
	  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
	  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
	  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  rack (1.6.4) lib/rack/lock.rb:17:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  railties (4.2.5) lib/rails/engine.rb:518:in `call'
	  railties (4.2.5) lib/rails/application.rb:165:in `call'
	  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
	  rack (1.6.4) lib/rack/lock.rb:17:in `call'
	  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
	  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
	  /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	  /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	  /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'


	  Rendered /home/felipe/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_source.erb (11.2ms)
	  Rendered /home/felipe/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_source.erb (11.2ms)
	  Rendered /home/felipe/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (6.7ms)
	  Rendered /home/felipe/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (6.7ms)
	  Rendered /home/felipe/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (3.2ms)
	  Rendered /home/felipe/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (3.2ms)
	  Rendered /home/felipe/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (59.5ms)
	  Rendered /home/felipe/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (59.5ms)

**Comment by beefoo** [comment]
What version of PostgresSQL are you using?  It looks like you may need to upgrade to version 9.4.x since I believe you're getting [this error](http://stackoverflow.com/questions/29393562/rails-and-jsonb-type-jsonb-does-not-exist).

**Comment by johnfelipe** [comment]
solved, tnks
